/* 
 * File:   mcal_intrrupt_gen_cfg.h
 * Author: Mahmoud Abdelmoniem
 *
 * Created on 26 , 2022, 06:29 
 */

#ifndef MCAL_INTRRUPT_GEN_CFG_H
#define	MCAL_INTRRUPT_GEN_CFG_H

#define INTERRUPT_FEATIRE_ENABLE   1U
#define EXTERNAL_INTERRUPT_INT0_FEATIRE_ENABLE     INTERRUPT_FEATIRE_ENABLE
#define EXTERNAL_INTERRUPT_PORTB_FEATIRE_ENABLE    INTERRUPT_FEATIRE_ENABLE


#define ADC_INTERRUPT_FEATIRE_ENABLE      INTERRUPT_FEATIRE_ENABLE
#define TIMER0_INTERRUPT_FEATIRE_ENABLE   INTERRUPT_FEATIRE_ENABLE
#define TIMER1_INTERRUPT_FEATIRE_ENABLE   INTERRUPT_FEATIRE_ENABLE
#define TIMER2_INTERRUPT_FEATIRE_ENABLE   INTERRUPT_FEATIRE_ENABLE
//#define CCP1_INTERRUPT_FEATIRE_ENABLE     INTERRUPT_FEATIRE_ENABLE
#define CCP2_INTERRUPT_FEATIRE_ENABLE     INTERRUPT_FEATIRE_ENABLE
#define USART_TX_INTERRUPT_FEATIRE_ENABLE    INTERRUPT_FEATIRE_ENABLE
#define USART_RX_INTERRUPT_FEATIRE_ENABLE    INTERRUPT_FEATIRE_ENABLE
#define SPI_INTERRUPT_FEATIRE_ENABLE        INTERRUPT_FEATIRE_ENABLE

//#define MSSP_I2C_INTERRUPT_FEATIRE_ENABLE    INTERRUPT_FEATIRE_ENABLE
#endif	/* MCAL_INTRRUPT_GEN_CFG_H */

